### ISSUE TITLE
[BUG] HUGE performance tank after 3.1.7 update

### ISSUE THREAD

**Issue by alesimula** [brendan-duncan/archive#183]
Hello, I've been using version 3.1.6 for a while now, and after upgrading to 3.1.9 (but I then noticed this issue was present since 3.1.7) performance absolutely tanked;

The file I used to test the library was [this one](https://www.apkmirror.com/apk/google-inc/google-search/google-search-12-41-16-release/google-app-12-41-16-23-x86_64-android-apk-download/);

I simply opened it via
```
ZipDecoder().decodeBytes(File("test.apk").readAsBytesSync());
```
It was almost immediate before 3.1.7; now it's so incredibly slow (orders of magnitude) I'm reverting to 3.1.6 until fixed

**Comment by brendan-duncan** [comment]
Thanks for letting me know, I'll look into it.

**Comment by brendan-duncan** [comment]
I published the performance regression fix, 3.1.10. The time to decode that apk went from ~3000ms to 67ms. Sorry about that, turns out List.removeWhere is incredibly slow when the number of files gets large.

**Comment by ekuleshov** [comment]
@brendan-duncan in the following code change, don't you have to renumber all values in the `_fileMap` that are greater than `fi` after removing element from the `files` list?

```
if (_fileMap.containsKey(file.name)) {
      var fi = _fileMap[file.name]!;
      _fileMap.remove(file.name);
      files.removeAt(fi);
}
```

**Comment by brendan-duncan** [comment]
I pushed a fix to 3.1.11. It doesn't need to remap the indices if I replace the files entry in-place,

**Comment by alesimula** [comment]
@brendan-duncan Hello, I have other few observations about performance and memory usage:

I tried these two different approaches for opening the test file I linked above:

```
var stream = InputFileStream(file.absolute.path);
return ZipDecoder().decodeBuffer(stream);
```
and
```
return ZipDecoder().decodeBytes(file.readAsBytesSync());
```

And noticed the second one, where I just passed the UInt8List obtained from readAsBytesSync, seems way faster than using the InputFileStream.

Initial memory usage also seemed to be way lower with the second approach, though, after some time, all memory used by the first method got cleaned up by the garbage collector, while the memory occupied using the second method would stay open indefinitely until I closed the application (hence why I also opened [this issue](https://github.com/brendan-duncan/archive/issues/180)).

It would be ideal to have a close method in the archive class I could call after I'm done using it, if that's possible.

Provided I don't know how the library (or compression) works, would it be possible to initially just read the archive header instead of its whole content, and make it so it would read the files "on demand" (so it would just store the initial and final offsets of each file's content)?

**Comment by brendan-duncan** [comment]
I would expect decoding the Uint8List would be faster. InputFileStream only keeps a 4k cache of the input file in memory, so there's a lot more file io. I am surprised to hear it uses more memory; I've heard from others, and would expect, InputFileStream to use significantly less memory.

The intent of the InputFileStream was to be able to not store file data, minimizing memory usage, equivalent to just storing the file offsets for the zip. However, I have very little time to work on this library, and InputFileStream is relatively new, so it hasn't gotten a lot of attention yet to make sure it works correctly.

I'm not sure I understand why closing an archive would be different than setting the archive object to null and letting the garbage collector deal with it. I can add an explicit close, it's just a matter of finding time.

**Comment by alesimula** [comment]
@brendan-duncan IDK but setting to null doesn't seem to free any memory, at least in my case (I'm running it in an Isolate, maybe that's what causing the issue)

**Comment by brendan-duncan** [comment]
Maybe something is hanging on the a reference to the Archive object so it's not getting garbage collected. I added a clear method. You can point the git version for now if you want to test it, it might be a bit before I release because I'll also see if I can finish up the InputFileStream work to where decoding a zip archive with it will not have to store the compressed data in memory. But I can't make promises when it'll get finished, work and life tend to get in the way.

**Comment by brendan-duncan** [comment]
I got a first pass of the FileInputStream and Archive refactoring in, where it can minimize memory usage by keeping as much data on disk as it can, instead of in memory. An Archive decoded from a FileInputStream, with have ArchiveFile's that have pointers to the archive file on disk. They can then be decompressed directly to disk, avoiding having to store the decompressed data in memory.

I updated the README with some info on it. I still need to test and profile it before I'll push a new version.

**Comment by alesimula** [comment]
@brendan-duncan I've tested the clear method, but it seems the program is still not freeing any memory.

If you want to test it, I am opening that apk file in an isolate; [this is the class in my program where I open the archive](https://github.com/alesimula/wsa_pacman/blob/main/lib/android/reader_apk.dart)

**Comment by brendan-duncan** [comment]
I don't have any control over Darts garbage collection or memory management. All I can do is clear the arrays.

**Comment by alesimula** [comment]
@brendan-duncan BTW I just noticed the clear method throws this exception:

`Exception: Unsupported operation: Cannot resize a fixed-length list`

**Comment by brendan-duncan** [comment]
Thanks, I'll fix that. Guess my tests didn't catch it.

**Comment by brendan-duncan** [comment]
Also, to reduce memory, I added AssetFile.clear().

The ArchiveFile.content property decompresses the data on demand and stores the decompressed data for that file.
AssetFile.clear() will remove that decompressed data. Which means if you access the file content again, it will have to decompress it again; but if you're just getting the file content once, then the archive won't be hanging on to that data.

So you'd do something like:
```dart
final data = file.content;
file.clear(); // remove the archive's reference to data.
// do something with data
```
